version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studentdb
      - MYSQL_USER=student
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    labels:
      # Spring Boot will use these to build the JDBC URL
      org.springframework.boot.jdbc.parameters: 'useSSL=false&allowPublicKeyRetrieval=true'